---
pipeline:
  nova-compute:
    image: plugins/docker
    dockerfile: nova_compute/Dockerfile
    secrets: [docker_username, docker_password]
    registry: registry.webhosting.rug.nl
    repo: registry.webhosting.rug.nl/hpc/openstack-nova-compute
    tag: latest
  notify:
    image: drillster/drone-email
    host: smtp.rug.nl
    port: 25
    skip_verify: true
    from: drone@webhosting.rug.nl
    recipients: [e.m.a.rijpkema@rug.nl, w.k.nap@rug.nl]
    #recipients: [e.m.a.rijpkema@rug.nl, w.k.nap@rug.nl]
    recipients_only: true
    when:
      status: [success, changed, failure]
#  slack:
#    image: plugins/slack
#    webhook:
#    channel: docker
#    when:
#      branch: [master, merlin]
#      status: [success, failure]
